local druid = require("druid.druid")
local monarch = require("monarch.monarch")

function init(self)
	self.druid = druid.new(self)
	self.druid:new_button("button", function()
		monarch.back()
	end)
end


function update(self, dt)
	self.druid:update(dt)

	gui.set_enabled(gui.get_node("button"), not monarch.is_top("main"))
end

function on_input(self, action_id, action)
	self.druid:on_input(action_id, action)
end